all:

flashbootloader: usb-led-bootloader.hex
	avrdude -c usbtiny -p attiny85 -U flash:w:usb-led-bootloader.hex:i -B 20

flashfuse:
	avrdude -c usbtiny -p attiny85 -U lfuse:w:0xe1:m -U hfuse:w:0xdd:m -U efuse:w:0xfe:m -B 20

flash: micronucleus usb-led-firmware.hex
	./micronucleus --run usb-led-firmware.hex
